export const randomData = [
  {
    stpId: "STP-1",
    title: "HPLC Analysis of Active Ingredients",
    attachment: "HPLC_Analysis_Protocol.pdf",
    version: "1.0",
    effectiveDate: "01/01/2024",
    creationDate: "12/15/2023",
    reviewedBy: "Dr. Alice Johnson",
    approvedBy: "Mr. Bob Brown",
    department: "Quality Control",
    objective: "To quantify active ingredients in pharmaceutical formulations.",
    testProcedureDescription:
      "The procedure involves the preparation of samples followed by HPLC analysis.",
    testType: "Chemical",
    testMethodReference: "USP <621>",
    samplePreparation: "Dilute the sample to 10 mg/mL.",
    reagents: "Acetonitrile, Water, Phosphoric Acid.",
    equipment: "HPLC system, UV Detector.",
    calibration: "Calibrate the HPLC monthly.",
    environmental: "Room Temperature (20-25°C).",
    controlSample: "Use standard reference materials.",
    testParameters: "Retention time, Peak area.",
    safetyPrecautions: "Wear gloves and goggles when handling chemicals.",
    validationRequirements: "Follow SOP for validation.",
    calculationFormula:
      "Concentration = (Peak area of sample / Peak area of standard) * Concentration of standard.",
    lsl: "0.5",
    usl: "2.0",
    resultInterpretation: "Results are acceptable if within LSL and USL.",
    expectedResults: "Expected range: 0.6 - 1.5 mg/mL.",
    reportTemplate: "Standard Analytical Report.",
    dataRecording: "Record in LIMS.",
    testFrequency: "Per Batch.",
    testReportSubmission: "Submit to QA within 5 business days.",
    deviationHandling: "Report any deviations immediately.",
    auditTrail: "Maintain an audit trail for all changes.",
    revisionHistory: "Log changes in revision history.",
    attachments: "Related documents include user manuals.",
    remarks: "Ensure all reagents are fresh.",
  },
  {
    stpId: "STP-2",
    title: "Microbial Testing for Raw Materials",
    attachment: "Microbial_Testing_Protocol.pdf",
    version: "1.2",
    effectiveDate: "01/15/2024",
    creationDate: "01/01/2023",
    reviewedBy: "Ms. Sarah Connor",
    approvedBy: "Dr. John Smith",
    department: "Microbiology",
    objective: "To detect microbial contamination in raw materials.",
    testProcedureDescription: "Samples are inoculated on selective media.",
    testType: "Microbiological",
    testMethodReference: "EP 2.6.12",
    samplePreparation: "Homogenize the sample and dilute appropriately.",
    reagents: "Nutrient Agar, Sabouraud Dextrose Agar.",
    equipment: "Incubator, Autoclave.",
    calibration: "Calibrate the incubator every 6 months.",
    environmental: "Incubator at 30-35°C.",
    controlSample: "Include positive and negative controls.",
    testParameters: "Colony counts.",
    safetyPrecautions: "Follow biosafety guidelines.",
    validationRequirements: "Perform validation annually.",
    calculationFormula: "Colony Forming Units (CFU)/g.",
    lsl: "N/A",
    usl: "100 CFU/g",
    resultInterpretation: "Acceptable if CFU is below USL.",
    expectedResults: "Expected CFU: < 10 CFU/g.",
    reportTemplate: "Microbial Test Report.",
    dataRecording: "Log data in Microbial Testing Log.",
    testFrequency: "Each batch of raw materials.",
    testReportSubmission: "Submit within 3 business days.",
    deviationHandling: "Document deviations in a deviation log.",
    auditTrail: "Keep records for audits.",
    revisionHistory: "Update when procedures change.",
    attachments: "Related microbial testing SOPs.",
    remarks: "Ensure all media are properly prepared.",
  },
  {
    stpId: "STP-3",
    title: "Dissolution Testing for Tablets",
    attachment: "Dissolution_Test_Protocol.pdf",
    version: "2.0",
    effectiveDate: "02/01/2024",
    creationDate: "01/10/2023",
    reviewedBy: "Mr. Mark Taylor",
    approvedBy: "Dr. Emily White",
    department: "Quality Control",
    objective: "To determine the dissolution rate of tablets.",
    testProcedureDescription: "Dissolution apparatus is used to test the samples.",
    testType: "Physical",
    testMethodReference: "USP <711>",
    samplePreparation: "Place tablets in dissolution media.",
    reagents: "Phosphate Buffer (pH 6.8).",
    equipment: "Dissolution Apparatus, UV Spectrophotometer.",
    calibration: "Calibrate the UV spectrophotometer weekly.",
    environmental: "Maintain temperature at 37°C.",
    controlSample: "Use standard dissolution tablets.",
    testParameters: "Dissolution rate at 30 min.",
    safetyPrecautions: "Handle with care to avoid burns.",
    validationRequirements: "Validation must be conducted every year.",
    calculationFormula: "Dissolution % = (Amount dissolved / Total amount) * 100.",
    lsl: "80%",
    usl: "120%",
    resultInterpretation: "Results are acceptable if between LSL and USL.",
    expectedResults: "Dissolution should be ≥ 85% in 30 minutes.",
    reportTemplate: "Dissolution Test Report.",
    dataRecording: "Document results in the Lab Notebook.",
    testFrequency: "Each production batch.",
    testReportSubmission: "Submit results to QA immediately.",
    deviationHandling: "Investigate any results outside the range.",
    auditTrail: "Document any modifications in protocols.",
    revisionHistory: "Record all changes made.",
    attachments: "SOP for Dissolution Testing.",
    remarks: "Check all equipment calibration.",
  },
  {
    stpId: "STP-4",
    title: "pH Testing for Solutions",
    attachment: "pH_Test_Protocol.pdf",
    version: "1.1",
    effectiveDate: "01/30/2024",
    creationDate: "12/20/2023",
    reviewedBy: "Ms. Lisa Ray",
    approvedBy: "Dr. Richard Black",
    department: "Quality Control",
    objective: "To measure the pH of pharmaceutical solutions.",
    testProcedureDescription: "Use a calibrated pH meter for testing.",
    testType: "Chemical",
    testMethodReference: "USP <791>",
    samplePreparation: "Prepare solutions as specified.",
    reagents: "Buffer solutions for calibration.",
    equipment: "pH Meter, Magnetic Stirrer.",
    calibration: "Calibrate pH meter daily.",
    environmental: "Room Temperature (20-25°C).",
    controlSample: "Use standard buffer solutions.",
    testParameters: "pH value.",
    safetyPrecautions: "Handle pH meter carefully.",
    validationRequirements: "Perform annual validation.",
    calculationFormula: "N/A",
    lsl: "5.0",
    usl: "7.0",
    resultInterpretation: "Acceptable if pH is within range.",
    expectedResults: "Expected pH: 6.0.",
    reportTemplate: "pH Test Report.",
    dataRecording: "Log results in Lab Notebook.",
    testFrequency: "Daily for solutions.",
    testReportSubmission: "Submit within 24 hours.",
    deviationHandling: "Document any deviations immediately.",
    auditTrail: "Maintain records for audits.",
    revisionHistory: "Log changes in revision history.",
    attachments: "pH Meter Calibration SOP.",
    remarks: "Check calibration before testing.",
  },
  {
    stpId: "STP-5",
    title: "Stability Testing for Finished Products",
    attachment: "Stability_Testing_Protocol.pdf",
    version: "3.0",
    effectiveDate: "03/01/2024",
    creationDate: "02/01/2023",
    reviewedBy: "Mr. Sam Wilson",
    approvedBy: "Dr. Nancy Drew",
    department: "Quality Control",
    objective: "To assess the stability of finished pharmaceutical products.",
    testProcedureDescription: "Samples are stored under specified conditions.",
    testType: "Physical",
    testMethodReference: "ICH Q1A",
    samplePreparation: "Store products at 25°C/60% RH.",
    reagents: "N/A",
    equipment: "Stability Chambers.",
    calibration: "Calibrate stability chambers quarterly.",
    environmental: "Controlled temperature and humidity.",
    controlSample: "Retain samples for comparison.",
    testParameters: "Appearance, Assay, Degradation products.",
    safetyPrecautions: "Ensure safe handling of products.",
    validationRequirements: "Conduct validation every two years.",
    calculationFormula: "N/A",
    lsl: "N/A",
    usl: "N/A",
    resultInterpretation: "Results to be documented in stability report.",
    expectedResults: "Product should meet specifications.",
    reportTemplate: "Stability Test Report.",
    dataRecording: "Document in Stability Log.",
    testFrequency: "Every 3 months.",
    testReportSubmission: "Submit to QA every 6 months.",
    deviationHandling: "Report any deviations immediately.",
    auditTrail: "Maintain audit records.",
    revisionHistory: "Update when procedures change.",
    attachments: "SOP for Stability Testing.",
    remarks: "Ensure conditions are monitored.",
  },
  {
    stpId: "STP-6",
    title: "Heavy Metal Testing for Raw Materials",
    attachment: "Heavy_Metal_Testing_Protocol.pdf",
    version: "1.0",
    effectiveDate: "02/15/2024",
    creationDate: "01/05/2023",
    reviewedBy: "Dr. Peter Parker",
    approvedBy: "Ms. Mary Jane",
    department: "Quality Control",
    objective: "To quantify heavy metals in raw materials.",
    testProcedureDescription: "Use AAS for heavy metal determination.",
    testType: "Chemical",
    testMethodReference: "USP <231>",
    samplePreparation: "Digest sample using acid.",
    reagents: "Nitric Acid, Hydrochloric Acid.",
    equipment: "Atomic Absorption Spectrophotometer.",
    calibration: "Calibrate AAS every month.",
    environmental: "Room Temperature (20-25°C).",
    controlSample: "Use certified reference materials.",
    testParameters: "Lead, Cadmium, Arsenic levels.",
    safetyPrecautions: "Wear protective gear when handling acids.",
    validationRequirements: "Validation to be done annually.",
    calculationFormula:
      "Concentration = (Absorbance of sample / Absorbance of standard) * Concentration of standard.",
    lsl: "0.1 mg/kg",
    usl: "10 mg/kg",
    resultInterpretation: "Results are acceptable if within limits.",
    expectedResults: "Expected lead level: < 1 mg/kg.",
    reportTemplate: "Heavy Metal Test Report.",
    dataRecording: "Record in LIMS.",
    testFrequency: "Each batch of raw materials.",
    testReportSubmission: "Submit to QA within 5 business days.",
    deviationHandling: "Report deviations immediately.",
    auditTrail: "Document all changes in records.",
    revisionHistory: "Log all updates to procedures.",
    attachments: "Related heavy metal testing SOPs.",
    remarks: "Ensure reagents are fresh.",
  },
  {
    stpId: "STP-7",
    title: "Viscosity Testing for Liquids",
    attachment: "Viscosity_Test_Protocol.pdf",
    version: "1.3",
    effectiveDate: "02/20/2024",
    creationDate: "12/30/2023",
    reviewedBy: "Ms. Jane Austen",
    approvedBy: "Dr. Henry James",
    department: "Quality Control",
    objective: "To measure the viscosity of liquid formulations.",
    testProcedureDescription: "Use a viscometer to measure viscosity.",
    testType: "Physical",
    testMethodReference: "ASTM D445",
    samplePreparation: "Ensure samples are at 25°C.",
    reagents: "N/A",
    equipment: "Brookfield Viscometer.",
    calibration: "Calibrate viscometer weekly.",
    environmental: "Maintain constant temperature.",
    controlSample: "Use standard viscosity fluids.",
    testParameters: "Viscosity in cP.",
    safetyPrecautions: "Handle samples carefully to avoid spills.",
    validationRequirements: "Annual validation required.",
    calculationFormula: "N/A",
    lsl: "1.0 cP",
    usl: "1000 cP",
    resultInterpretation: "Results are acceptable if within limits.",
    expectedResults: "Expected viscosity: 20-50 cP.",
    reportTemplate: "Viscosity Test Report.",
    dataRecording: "Log results in Viscosity Testing Log.",
    testFrequency: "Every batch of liquid products.",
    testReportSubmission: "Submit within 2 business days.",
    deviationHandling: "Document deviations immediately.",
    auditTrail: "Keep a detailed audit trail.",
    revisionHistory: "Update documentation when procedures change.",
    attachments: "Viscometer SOP.",
    remarks: "Check equipment calibration before testing.",
  },
  {
    stpId: "STP-8",
    title: "Uniformity of Dosage Units Testing",
    attachment: "Uniformity_Test_Protocol.pdf",
    version: "2.1",
    effectiveDate: "03/15/2024",
    creationDate: "01/25/2023",
    reviewedBy: "Mr. Tim Howard",
    approvedBy: "Dr. Clara Oswald",
    department: "Quality Control",
    objective: "To ensure uniformity in dosage units.",
    testProcedureDescription: "Test a specified number of units for dosage uniformity.",
    testType: "Physical",
    testMethodReference: "USP <905>",
    samplePreparation: "Select random samples from a batch.",
    reagents: "N/A",
    equipment: "Analytical balance.",
    calibration: "Calibrate balance weekly.",
    environmental: "Room Temperature (20-25°C).",
    controlSample: "Use reference tablets.",
    testParameters: "Weight variation.",
    safetyPrecautions: "Use gloves when handling samples.",
    validationRequirements: "Validation done every year.",
    calculationFormula: "Uniformity = (Weight of sample / Average weight) * 100.",
    lsl: "85%",
    usl: "115%",
    resultInterpretation: "Results are acceptable if within limits.",
    expectedResults: "Weight variation: < 10%.",
    reportTemplate: "Uniformity Test Report.",
    dataRecording: "Document results in the Lab Notebook.",
    testFrequency: "Each batch of tablets.",
    testReportSubmission: "Submit to QA immediately.",
    deviationHandling: "Investigate and report deviations.",
    auditTrail: "Maintain audit records.",
    revisionHistory: "Log any changes to procedures.",
    attachments: "Uniformity Testing SOP.",
    remarks: "Ensure the balance is calibrated.",
  },
  {
    stpId: "STP-9",
    title: "Cleaning Validation of Equipment",
    attachment: "Cleaning_Validation_Protocol.pdf",
    version: "1.0",
    effectiveDate: "03/10/2024",
    creationDate: "02/05/2023",
    reviewedBy: "Dr. Fiona Green",
    approvedBy: "Mr. David Blaine",
    department: "Quality Assurance",
    objective: "To ensure equipment is properly cleaned and validated.",
    testProcedureDescription: "Test residues on equipment after cleaning.",
    testType: "Chemical",
    testMethodReference: "FDA Guidance Document",
    samplePreparation: "Swab equipment surfaces for testing.",
    reagents: "Solvent for extraction.",
    equipment: "HPLC for residue analysis.",
    calibration: "Calibrate HPLC before use.",
    environmental: "Room Temperature (20-25°C).",
    controlSample: "Use a clean piece of equipment as a control.",
    testParameters: "Residue concentration.",
    safetyPrecautions: "Wear gloves and safety glasses.",
    validationRequirements: "Validation done annually.",
    calculationFormula: "Residue = (Amount found / Amount applied) * 100.",
    lsl: "N/A",
    usl: "0.1 mg/cm²",
    resultInterpretation: "Acceptable if residues are below USL.",
    expectedResults: "Residue levels: < 0.05 mg/cm².",
    reportTemplate: "Cleaning Validation Report.",
    dataRecording: "Log results in Cleaning Validation Log.",
    testFrequency: "After each cleaning cycle.",
    testReportSubmission: "Submit to QA within 5 business days.",
    deviationHandling: "Report and investigate deviations.",
    auditTrail: "Keep detailed records of validations.",
    revisionHistory: "Update procedures as needed.",
    attachments: "Cleaning Validation SOP.",
    remarks: "Ensure all equipment is accessible.",
  },
  {
    stpId: "STP-10",
    title: "Content Uniformity Testing for Powders",
    attachment: "Content_Uniformity_Test_Protocol.pdf",
    version: "1.1",
    effectiveDate: "03/20/2024",
    creationDate: "01/15/2023",
    reviewedBy: "Ms. Sarah Connor",
    approvedBy: "Dr. Alan Turing",
    department: "Quality Control",
    objective: "To confirm uniformity of active ingredients in powder forms.",
    testProcedureDescription: "Measure active ingredient in selected samples.",
    testType: "Chemical",
    testMethodReference: "USP <905>",
    samplePreparation: "Prepare sample from the batch.",
    reagents: "N/A",
    equipment: "Analytical Balance, UV Spectrophotometer.",
    calibration: "Calibrate equipment weekly.",
    environmental: "Room Temperature (20-25°C).",
    controlSample: "Use standards for comparison.",
    testParameters: "Content uniformity.",
    safetyPrecautions: "Handle chemicals with care.",
    validationRequirements: "Perform validation every year.",
    calculationFormula: "Uniformity % = (Measured amount / Label claim) * 100.",
    lsl: "85%",
    usl: "115%",
    resultInterpretation: "Acceptable if within limits.",
    expectedResults: "Uniformity should be > 95%.",
    reportTemplate: "Content Uniformity Test Report.",
    dataRecording: "Log results in Lab Notebook.",
    testFrequency: "Each production batch.",
    testReportSubmission: "Submit to QA within 3 business days.",
    deviationHandling: "Document any deviations immediately.",
    auditTrail: "Maintain audit records for compliance.",
    revisionHistory: "Update documentation as required.",
    attachments: "SOP for Content Uniformity Testing.",
    remarks: "Ensure equipment is calibrated before use.",
  },
];
