export const randomSpecData = [
    {
        specId: "SPEC-1",
        title: "Active Ingredient Assay Specification",
        version: "1.0",
        attachment: "Active_Ingredient_Assay.pdf",
        effectiveDate: "01/01/2024",
        creationDate: "12/01/2023",
        approvedBy: "Dr. Alice Johnson",
        productName: "Paracetamol",
        batchLotNumber: "Batch-12345",
        productCategory: "Finished Product",
        manufacturer: "Pharma Co.",
        description: "White crystalline powder.",
        materialGrade: "Pharmaceutical grade",
        molecularFormula: "C8H9NO2",
        packagingRequirements: "Pack in airtight containers.",
        storageConditions: "Store at room temperature.",
        shelfLife: "2 years",
        labelingRequirements: "Include batch number and expiry date.",
        testParameter: "Assay",
        testMethod: "USP <541>",
        acceptanceCriteria: "98.0% - 102.0%",
        unitsOfMeasurement: "%",
        testFrequency: "Each batch",
        controlSampleReference: "Use standard Paracetamol for calibration.",
        samplingPlan: "Random sampling from production batch.",
        testMethodValidation: "Method is validated.",
        referenceStandards: "USP reference standard.",
        resultInterpretation: "Results are acceptable if within criteria.",
        stabilityCriteria: "Stable under recommended storage conditions.",
        reTestingInterval: "Every 6 months.",
        regulatoryRequirements: "FDA, GMP compliant.",
        certification: "ISO 9001",
        deviationHandling: "Follow SOP for deviations.",
        auditTrail: "Document all changes.",
        documentReference: "Certificate of Analysis (CoA).",
        revisionHistory: "Updated for version control.",
        attachments: "Validation report attached.",
        comments: "Review annually.",
        reviewFrequency: "Every year",
        expiryDate: "01/01/2026",
        status: "Active",
    },
    {
        specId: "SPEC-2",
        title: "Stability Specification for Active Ingredients",
        version: "1.1",
        attachment: "Stability_Specification.pdf",
        effectiveDate: "01/15/2024",
        creationDate: "01/05/2023",
        approvedBy: "Mr. Bob Brown",
        productName: "Ibuprofen",
        batchLotNumber: "Batch-54321",
        productCategory: "Intermediate",
        manufacturer: "HealthCorp.",
        description: "Off-white powder.",
        materialGrade: "Pharmaceutical grade",
        molecularFormula: "C13H18O2",
        packagingRequirements: "Store in light-resistant containers.",
        storageConditions: "Refrigerate at 2-8°C.",
        shelfLife: "3 years",
        labelingRequirements: "Batch number and storage instructions.",
        testParameter: "Degradation Products",
        testMethod: "ICH Q1A",
        acceptanceCriteria: "Less than 1% degradation.",
        unitsOfMeasurement: "%",
        testFrequency: "Every year.",
        controlSampleReference: "Use standard for comparison.",
        samplingPlan: "Stratified sampling from batches.",
        testMethodValidation: "Validation done annually.",
        referenceStandards: "ICH stability guidelines.",
        resultInterpretation: "Results acceptable if within criteria.",
        stabilityCriteria: "Data from stability studies.",
        reTestingInterval: "Annually.",
        regulatoryRequirements: "WHO compliant.",
        certification: "CoA available.",
        deviationHandling: "Report any deviations.",
        auditTrail: "Maintain records for all tests.",
        documentReference: "Stability study reports.",
        revisionHistory: "Reviewed every 6 months.",
        attachments: "SOP for stability testing.",
        comments: "Check for environmental conditions.",
        reviewFrequency: "Every six months",
        expiryDate: "01/15/2027",
        status: "Active",
    },
    {
        specId: "SPEC-3",
        title: "Quality Specification for Raw Materials",
        version: "1.0",
        attachment: "Raw_Materials_Specification.pdf",
        effectiveDate: "02/01/2024",
        creationDate: "12/15/2023",
        approvedBy: "Dr. John Smith",
        productName: "Sodium Chloride",
        batchLotNumber: "Lot-001122",
        productCategory: "Raw Material",
        manufacturer: "Chemical Inc.",
        description: "White crystalline solid.",
        materialGrade: "Food grade",
        molecularFormula: "NaCl",
        packagingRequirements: "Use moisture-proof bags.",
        storageConditions: "Store in a cool, dry place.",
        shelfLife: "Indefinite when stored properly.",
        labelingRequirements: "Batch number and supplier information.",
        testParameter: "Purity",
        testMethod: "USP <201>",
        acceptanceCriteria: "Min 99.0% purity.",
        unitsOfMeasurement: "%",
        testFrequency: "Each shipment.",
        controlSampleReference: "Use certified reference material.",
        samplingPlan: "Random sampling from the shipment.",
        testMethodValidation: "Validation required every year.",
        referenceStandards: "USP standards.",
        resultInterpretation: "Results acceptable if within criteria.",
        stabilityCriteria: "Stable under specified conditions.",
        reTestingInterval: "Annually.",
        regulatoryRequirements: "GMP compliant.",
        certification: "ISO 22000",
        deviationHandling: "Document deviations in the log.",
        auditTrail: "Maintain a detailed audit trail.",
        documentReference: "Certificate of Authenticity.",
        revisionHistory: "Version history maintained.",
        attachments: "Material Safety Data Sheet (MSDS).",
        comments: "Ensure proper storage conditions.",
        reviewFrequency: "Every two years",
        expiryDate: "N/A",
        status: "Active",
    },
    {
        specId: "SPEC-4",
        title: "Assay Specification for Finished Products",
        version: "1.2",
        attachment: "Finished_Product_Assay.pdf",
        effectiveDate: "01/30/2024",
        creationDate: "12/20/2023",
        approvedBy: "Ms. Jane Doe",
        productName: "Aspirin",
        batchLotNumber: "Lot-98765",
        productCategory: "Finished Product",
        manufacturer: "Pharma Solutions.",
        description: "White, crystalline powder.",
        materialGrade: "USP grade",
        molecularFormula: "C9H8O4",
        packagingRequirements: "Pack in airtight containers.",
        storageConditions: "Store at room temperature.",
        shelfLife: "2 years",
        labelingRequirements: "Include product name and batch number.",
        testParameter: "Assay",
        testMethod: "USP <401>",
        acceptanceCriteria: "97.0% - 103.0%",
        unitsOfMeasurement: "%",
        testFrequency: "Each batch.",
        controlSampleReference: "Use USP reference standard.",
        samplingPlan: "Random sampling from production.",
        testMethodValidation: "Method validated and approved.",
        referenceStandards: "USP assay standards.",
        resultInterpretation: "Results acceptable if within limits.",
        stabilityCriteria: "Stable for the duration of shelf life.",
        reTestingInterval: "Re-test every 6 months.",
        regulatoryRequirements: "FDA compliant.",
        certification: "ISO 13485",
        deviationHandling: "Follow established deviation procedures.",
        auditTrail: "Document changes in the audit log.",
        documentReference: "Analytical Test Report.",
        revisionHistory: "Reviewed bi-annually.",
        attachments: "Testing SOP included.",
        comments: "Ensure proper calibration of equipment.",
        reviewFrequency: "Every year",
        expiryDate: "01/30/2026",
        status: "Active",
    },
    {
        specId: "SPEC-5",
        title: "Packaging Specification for Liquid Products",
        version: "1.0",
        attachment: "Liquid_Packaging_Specification.pdf",
        effectiveDate: "02/15/2024",
        creationDate: "01/10/2023",
        approvedBy: "Mr. Tim Brown",
        productName: "Liquid Antiseptic",
        batchLotNumber: "Batch-2023A",
        productCategory: "Finished Product",
        manufacturer: "CleanTech Corp.",
        description: "Clear liquid with characteristic odor.",
        materialGrade: "Pharmaceutical grade",
        molecularFormula: "N/A",
        packagingRequirements: "Bottles with child-resistant caps.",
        storageConditions: "Keep in a cool, dry place.",
        shelfLife: "1 year",
        labelingRequirements: "Batch number and usage instructions.",
        testParameter: "Container integrity",
        testMethod: "Visual inspection.",
        acceptanceCriteria: "No leaks or damages.",
        unitsOfMeasurement: "N/A",
        testFrequency: "Every production batch.",
        controlSampleReference: "Use a control sample for comparison.",
        samplingPlan: "Random sampling from finished products.",
        testMethodValidation: "Validation performed for packaging.",
        referenceStandards: "Internal standards.",
        resultInterpretation: "Acceptable if containers are intact.",
        stabilityCriteria: "Product must remain stable in packaging.",
        reTestingInterval: "Yearly for packaging validation.",
        regulatoryRequirements: "Compliant with FDA regulations.",
        certification: "ISO 15378",
        deviationHandling: "Report and investigate any packaging failures.",
        auditTrail: "Keep detailed records of packaging tests.",
        documentReference: "Packaging Test Report.",
        revisionHistory: "Updated with each version.",
        attachments: "Packaging SOP included.",
        comments: "Verify caps and seals before use.",
        reviewFrequency: "Every year",
        expiryDate: "02/15/2025",
        status: "Active",
    },
    {
        specId: "SPEC-6",
        title: "Chemical Specification for Solvents",
        version: "2.0",
        attachment: "Solvent_Chemical_Specification.pdf",
        effectiveDate: "01/20/2024",
        creationDate: "12/28/2023",
        approvedBy: "Dr. Clara White",
        productName: "Methanol",
        batchLotNumber: "Lot-5555",
        productCategory: "Raw Material",
        manufacturer: "Solvent Manufacturers Inc.",
        description: "Colorless, volatile liquid.",
        materialGrade: "Reagent grade",
        molecularFormula: "CH3OH",
        packagingRequirements: "Tightly sealed glass bottles.",
        storageConditions: "Store in a cool, ventilated area.",
        shelfLife: "Indefinite when stored properly.",
        labelingRequirements: "Proper hazard labeling required.",
        testParameter: "Purity",
        testMethod: "ASTM D1613",
        acceptanceCriteria: "≥ 99.8% purity.",
        unitsOfMeasurement: "%",
        testFrequency: "Each batch received.",
        controlSampleReference: "Certified reference standard.",
        samplingPlan: "Random sampling from received batches.",
        testMethodValidation: "Validation required every year.",
        referenceStandards: "ASTM standards.",
        resultInterpretation: "Results acceptable if above criteria.",
        stabilityCriteria: "Stable under recommended storage.",
        reTestingInterval: "Every 12 months.",
        regulatoryRequirements: "Meets EPA regulations.",
        certification: "ISO 17025",
        deviationHandling: "Follow internal procedures for deviations.",
        auditTrail: "Document all tests and modifications.",
        documentReference: "Certificate of Analysis (CoA).",
        revisionHistory: "Log all revisions.",
        attachments: "Safety Data Sheet (SDS) included.",
        comments: "Ensure proper ventilation during storage.",
        reviewFrequency: "Every year",
        expiryDate: "N/A",
        status: "Active",
    },
    {
        specId: "SPEC-7",
        title: "Test Specification for Viscosity",
        version: "1.1",
        attachment: "Viscosity_Test_Specification.pdf",
        effectiveDate: "02/10/2024",
        creationDate: "01/05/2023",
        approvedBy: "Ms. Linda Grey",
        productName: "Syrup",
        batchLotNumber: "Lot-SYRUP2023",
        productCategory: "Finished Product",
        manufacturer: "Sweet Solutions Ltd.",
        description: "Thick, sweet liquid.",
        materialGrade: "Food grade",
        molecularFormula: "N/A",
        packagingRequirements: "Use food-safe plastic containers.",
        storageConditions: "Store at room temperature.",
        shelfLife: "1 year",
        labelingRequirements: "Product name and batch number.",
        testParameter: "Viscosity",
        testMethod: "ASTM D2196",
        acceptanceCriteria: "200 - 500 cP.",
        unitsOfMeasurement: "cP",
        testFrequency: "Each batch.",
        controlSampleReference: "Use control syrup for comparison.",
        samplingPlan: "Random sampling from production.",
        testMethodValidation: "Method validated.",
        referenceStandards: "ASTM standards for viscosity.",
        resultInterpretation: "Results acceptable if within limits.",
        stabilityCriteria: "Stable for the duration of shelf life.",
        reTestingInterval: "Annually.",
        regulatoryRequirements: "FDA compliant.",
        certification: "ISO 22000",
        deviationHandling: "Document deviations according to SOP.",
        auditTrail: "Maintain records of all viscosity tests.",
        documentReference: "Testing SOP included.",
        revisionHistory: "Reviewed quarterly.",
        attachments: "Testing equipment SOP.",
        comments: "Check equipment calibration regularly.",
        reviewFrequency: "Every six months",
        expiryDate: "02/10/2025",
        status: "Active",
    },
    {
        specId: "SPEC-8",
        title: "Cleaning Specification for Equipment",
        version: "1.0",
        attachment: "Cleaning_Specification.pdf",
        effectiveDate: "02/20/2024",
        creationDate: "12/15/2023",
        approvedBy: "Mr. James Carter",
        productName: "Production Equipment",
        batchLotNumber: "Batch-001",
        productCategory: "Equipment",
        manufacturer: "Machinery Inc.",
        description: "Stainless steel manufacturing equipment.",
        materialGrade: "Industrial grade",
        molecularFormula: "N/A",
        packagingRequirements: "N/A",
        storageConditions: "Keep clean and dry.",
        shelfLife: "Indefinite when maintained properly.",
        labelingRequirements: "N/A",
        testParameter: "Residue Testing",
        testMethod: "Visual Inspection",
        acceptanceCriteria: "No residues visible.",
        unitsOfMeasurement: "N/A",
        testFrequency: "After each use.",
        controlSampleReference: "Use clean equipment as reference.",
        samplingPlan: "N/A",
        testMethodValidation: "Validation performed annually.",
        referenceStandards: "Internal cleaning standards.",
        resultInterpretation: "Acceptable if no residues detected.",
        stabilityCriteria: "Maintain cleanliness over time.",
        reTestingInterval: "After major production runs.",
        regulatoryRequirements: "Meets safety regulations.",
        certification: "N/A",
        deviationHandling: "Report any cleaning failures.",
        auditTrail: "Keep detailed cleaning records.",
        documentReference: "Cleaning Validation Report.",
        revisionHistory: "Reviewed every year.",
        attachments: "Cleaning SOP included.",
        comments: "Ensure all surfaces are reachable.",
        reviewFrequency: "Every year",
        expiryDate: "N/A",
        status: "Active",
    },
    {
        specId: "SPEC-9",
        title: "Specification for Analytical Standards",
        version: "1.2",
        attachment: "Analytical_Standards_Specification.pdf",
        effectiveDate: "03/01/2024",
        creationDate: "01/01/2023",
        approvedBy: "Dr. Lucy Hale",
        productName: "Analytical Reagents",
        batchLotNumber: "Batch-REAG2023",
        productCategory: "Reagents",
        manufacturer: "Reagent Suppliers Co.",
        description: "High-purity analytical reagents.",
        materialGrade: "ACS grade",
        molecularFormula: "N/A",
        packagingRequirements: "Store in tightly sealed bottles.",
        storageConditions: "Store in a cool, dry place.",
        shelfLife: "Indefinite when stored properly.",
        labelingRequirements: "Include purity and lot number.",
        testParameter: "Purity and Stability",
        testMethod: "ASTM E1693",
        acceptanceCriteria: "≥ 99.0% purity.",
        unitsOfMeasurement: "%",
        testFrequency: "Per shipment.",
        controlSampleReference: "Use standard reference materials.",
        samplingPlan: "Random sampling from each shipment.",
        testMethodValidation: "Validation required annually.",
        referenceStandards: "Use ACS reference standards.",
        resultInterpretation: "Acceptable if purity is within limits.",
        stabilityCriteria: "Stable under recommended conditions.",
        reTestingInterval: "Every year.",
        regulatoryRequirements: "Compliant with ANSI standards.",
        certification: "ISO 17034",
        deviationHandling: "Document deviations according to SOP.",
        auditTrail: "Maintain records for all tests.",
        documentReference: "Certificate of Analysis (CoA).",
        revisionHistory: "Updated annually.",
        attachments: "Testing SOP included.",
        comments: "Ensure reagents are fresh.",
        reviewFrequency: "Every year",
        expiryDate: "N/A",
        status: "Active",
    },
    {
        specId: "SPEC-10",
        title: "Specification for Cleaning Agents",
        version: "1.0",
        attachment: "Cleaning_Agents_Specification.pdf",
        effectiveDate: "03/15/2024",
        creationDate: "02/01/2023",
        approvedBy: "Mr. Paul Walker",
        productName: "Sanitizing Solution",
        batchLotNumber: "Batch-CLEAN2023",
        productCategory: "Cleaning Agent",
        manufacturer: "Clean Solutions Inc.",
        description: "Clear liquid with disinfectant properties.",
        materialGrade: "Industrial grade",
        molecularFormula: "N/A",
        packagingRequirements: "Use chemical-resistant containers.",
        storageConditions: "Store away from direct sunlight.",
        shelfLife: "2 years",
        labelingRequirements: "Include hazard warnings.",
        testParameter: "Efficacy",
        testMethod: "EPA method 8101",
        acceptanceCriteria: "Kill rate of ≥ 99.9%.",
        unitsOfMeasurement: "%",
        testFrequency: "Each production batch.",
        controlSampleReference: "Use standard efficacy testing methods.",
        samplingPlan: "Random sampling from production lots.",
        testMethodValidation: "Validation done annually.",
        referenceStandards: "EPA standards for cleaning agents.",
        resultInterpretation: "Results acceptable if within limits.",
        stabilityCriteria: "Stable for the duration of shelf life.",
        reTestingInterval: "Annually.",
        regulatoryRequirements: "Compliant with EPA regulations.",
        certification: "N/A",
        deviationHandling: "Report deviations in testing logs.",
        auditTrail: "Keep records of testing and modifications.",
        documentReference: "Cleaning Agent Test Report.",
        revisionHistory: "Updated for version control.",
        attachments: "Safety Data Sheet (SDS) included.",
        comments: "Ensure all cleaning agents are used according to SOP.",
        reviewFrequency: "Every year",
        expiryDate: "03/15/2026",
        status: "Active",
    }
];
